version: '3.8'

services:
  start-loadbalancer:
    image: docker
    restart: on-failure
    command:
      - sh
      - /app/docker/traefik/traefik.sh
    environment:
      - DOCKER_HOST
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app

  # Adminer
  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: "pepa-linha"
      ADMINER_DEFAULT_SERVER: "db"
    depends_on:
      - db
    links:
      - db
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress-adminer.rule=Host(`adminer.${WORDPRESS_BLOGURL}`)"
      - "traefik.http.routers.wordpress-adminer.entrypoints=web"
      - "traefik.http.services.wordpress-adminer.loadbalancer.server.port=8080"

  db:
    image: mariadb:10.2.41
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    env_file:
      - ./docker/mysql/mysql.env
      - ./.env

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress-mailhog.rule=Host(`mailhog.${WORDPRESS_BLOGURL}`)"
      - "traefik.http.routers.wordpress-mailhog.entrypoints=web"
      - "traefik.http.services.wordpress-mailhog.loadbalancer.server.port=8025"

  nginx:
    image: nginx:stable
    links:
      - app
    networks:
      - traefik
      - default
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`${WORDPRESS_BLOGURL}`)"
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"

  app:
    build:
      context: .
      target: php-fpm
    links:
      - db
    env_file:
      - ./.env
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/html/.env
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/dev.php.ini

volumes:
  db:

networks:
  default:
  traefik:
    external: true