<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5zH4Onm\VAF_WP_Library_Kernel_PluginKernelDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5zH4Onm/VAF_WP_Library_Kernel_PluginKernelDebugContainer.php') {
    touch(__DIR__.'/Container5zH4Onm.legacy');

    return;
}

if (!\class_exists(VAF_WP_Library_Kernel_PluginKernelDebugContainer::class, false)) {
    \class_alias(\Container5zH4Onm\VAF_WP_Library_Kernel_PluginKernelDebugContainer::class, VAF_WP_Library_Kernel_PluginKernelDebugContainer::class, false);
}

return new \Container5zH4Onm\VAF_WP_Library_Kernel_PluginKernelDebugContainer([
    'container.build_hash' => '5zH4Onm',
    'container.build_id' => 'c48b0226',
    'container.build_time' => 1685222445,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5zH4Onm');
