<?php

namespace Container5zH4Onm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHook_LoaderService extends VAF_WP_Library_Kernel_PluginKernelDebugContainer
{
    /**
     * Gets the public 'hook.loader' shared autowired service.
     *
     * @return \VAF\WP\Library\Hook\Loader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 6).'/vendor/vonaffenfels/vaf-wp-library/src/Hook/Loader.php';

        return $container->services['hook.loader'] = new \VAF\WP\Library\Hook\Loader(($container->services['kernel'] ?? $container->get('kernel', 1)), ['VAF\\WP\\TestPlugin\\Hooks\\TestHook' => 'VAF\\WP\\TestPlugin\\Hooks\\TestHook']);
    }
}
